byebyebirdies/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  resources :birds
  resources :bird_rental_requests, only: [:new, :create]
end

byebyebirdies/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

byebyebirdies/app/models/bird.rb
# == Schema Information
#
# Table name: birds
#
#  id          :integer          not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text             not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

require 'action_view'

class Bird < ApplicationRecord
  COLORS = ["Blue", "Red", "Fuscia", "Purple",
    "Lime-Green", "Green", "Yellow", "Black", "Grey", "Gray", "Orange",
    "Salmon", "Pink", "Beige", "Olive", "Turqoise"]


  validates :birth_date, :color, :name, :sex, :description, presence: true
  validates :sex, inclusion: ["M", "F"]
  validates :color, inclusion: COLORS

  include ActionView::Helpers::DateHelper

  has_many :bird_rental_requests,
    primary_key: :id,
    foreign_key: :bird_id,
    class_name: "BirdRentalRequest",
    dependent: :destroy

  def age
    time_ago_in_words(self.birth_date)
  end

end

byebyebirdies/app/models/bird_rental_request.rb
# == Schema Information
#
# Table name: bird_rental_requests
#
#  id         :integer          not null, primary key
#  bird_id    :integer          not null
#  start_date :date             not null
#  end_date   :date             not null
#  status     :string           default("PENDING")
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class BirdRentalRequest < ApplicationRecord
  validates :status, inclusion: ["PENDING", "APPROVED", "DENIED"]
  validates :bird_id, :start_date, :end_date, presence: true
  validate :does_not_overlap_approved_request

  belongs_to :bird,
    primary_key: :id,
    foreign_key: :bird_id,
    class_name: "Bird"

  def overlapping_requests
    BirdRentalRequest
      .where(bird_id: self.bird_id)
      .where('NOT (end_date < ? OR start_date > ?)',
        self.start_date, self.end_date)
  end

  def overlapping_approved_requests
    overlapping_requests
      .where(status: "APPROVED")
  end

  def overlapping_pending_requests
    overlapping_requests
      .where(status: "PENDING")
  end

  def does_not_overlap_approved_request
    errors[:overlap] << "Overlapping Request" if overlapping_approved_requests.exists?
  end

  def approve!
    ActiveRecord::Base.transaction do
      self.status = "APPROVED"
      self.save
      overlapping_pending_requests.each { |request| request.deny! }
    end
  end

  def deny!
    self.status = "DENIED"
    self.update_attributes
  end

end

byebyebirdies/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
end

byebyebirdies/app/controllers/bird_rental_requests_controller.rb
class BirdRentalRequestsController < ApplicationController
  def new
    @request = BirdRentalRequest.new
  end

  def create
    @request = BirdRentalRequest.new(bird_rental_request_params)

    if @request.save
      redirect_to bird_url(@request.bird)
    else
      render :new
    end
  end

  private
  def bird_rental_request_params
    params.require(:request).permit(:start_date, :end_date, :bird_id)
  end
end

byebyebirdies/app/controllers/birds_controller.rb
class BirdsController < ApplicationController
  def index
    @birds = Bird.all
  end

  def create

    @bird = Bird.new(bird_params)

    if @bird.save
      redirect_to bird_url(@bird)
    else
      render :new
    end
  end

  def new
    @bird = Bird.new
    #
    # render :new
  end

  def edit
    @bird = Bird.find(params[:id])
  end

  def show
    @bird = Bird.find(params[:id])
  end

  def update
    @bird = Bird.find(params[:id])

    if @bird.update_attributes(bird_params)
      redirect_to bird_url(@bird)
    else
      render :new
    end
  end

  def destroy

  end

  private
  def bird_params
    params.require(:bird).permit(:birth_date, :color, :name, :sex, :description)
  end
end

byebyebirdies/app/helpers/application_helper.rb
module ApplicationHelper
end

byebyebirdies/app/helpers/bird_controller_helper.rb
module BirdControllerHelper
end

byebyebirdies/app/helpers/bird_rental_requests_controller_helper.rb
module BirdRentalRequestsControllerHelper
end

byebyebirdies/app/views/bird_rental_requests/new.html.erb
<form action="/bird_rental_requests" method="post">

  <label for="bird_id">Bird's Name:</label>
  <select id="bird_id" name="request[bird_id]">
    <option disabled selected >
      -- Please Select --
    </option>

    <% Bird.all.each do |bird| %>
      <option id="bird_id" value="<%= bird.id %>" ><%= bird.name %></option>
    <% end %>
  </select>

  <br>
  <br>

  <label for="start_date">Start Date:</label>
  <input id="start_date" type="date" name="request[start_date]"
  value =  "<%= @request.start_date %>" >

  <br>
  <br>

  <label for="end_date">End Date:</label>
  <input id="end_date" type="date" name="request[end_date]"
  value =  "<%= @request.end_date %>" >

  <br>
  <br>

  <input type="submit" value="Submit Birdquest">

</form>

byebyebirdies/app/views/birds/_bird.html.erb
<li>
  <%= bird.name %> 
</li>

byebyebirdies/app/views/birds/_form.html.erb
<% action_url = (action == :edit ? bird_url : birds_url) %>

<form action="<%= action_url %>" method="post">
  <% if action == :edit %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>

  <label for="name">Name:</label>
  <input id="name" type="text" name="bird[name]" value="<%= action == :edit ? @bird.name : "" %>">

  <br>
  <br>

  <label for="sex">Sex:</label>
  <input id="sex" type="radio" name="bird[sex]" value="M" <%= "M" == @bird.sex ? "checked" : "" %>> Male
  <input id="sex" type="radio" name="bird[sex]" value="F" <%= "F" == @bird.sex ? "checked" : "" %>> Female

  <br>
  <br>

  <label for="color">Color:</label>
  <select id="color" name="bird[color]">
    <option disabled <%= action == :edit ? "" : "selected" %> >
      -- Please Select --
    </option>

    <% Bird::COLORS.each do |color| %>
      <option id="color" value="<%= color %>" <%= color == @bird.color ? "selected" : "" %> ><%= color %></option>
    <% end %>
  </select>

  <br>
  <br>

  <label for="birth_date">Birth Date:</label>
  <input id="birth_date" type="date" name="bird[birth_date]"
  value =  "<%= @bird.birth_date %>" >

  <br>
  <br>

  <label for="description">Description:</label>
  <textarea id="description" name="bird[description]"> <%= @bird.description %> </textarea>

  <br>
  <br>

  <input type="submit" value="<%= action == :edit ? "Edit Bird" : "Add Bird" %>">

</form>

byebyebirdies/app/views/birds/edit.html.erb
<h1>Change your birdie! *chirp chirp*</h1>

<%= render "form", bird: @bird, action: :edit %>

byebyebirdies/app/views/birds/index.html.erb
<h1>The Whole Flock</h1>

<ul>
  <% @birds.each do |bird| %>
    <%= render bird %>
    <%= link_to "Quack me out", bird_url(bird) %>
    <% end %>
</ul>

<%= link_to "Add Bird", new_bird_url %>

byebyebirdies/app/views/birds/new.html.erb
<h1>Register your birdie! *chirp chirp*</h1>

<%= render "form", bird: @bird, action: :new %>

byebyebirdies/app/views/birds/show.html.erb
<h1>  <%= @bird.name %> </h1>
<br>

<img src="https://lafeber.com/pet-birds/wp-content/uploads/iStock_5307869green-cheeck-conure.jpg">

<br>

<table>
  <tr>
    <td>Name:</td>
    <td><%= @bird.name %></td>
  </tr>
  <tr>
    <td>Age:</td>
    <td><%= @bird.age %></td>
  </tr>
  <tr>
    <td>Color:</td>
    <td><%= @bird.color %></td>
  </tr>
  <tr>
    <td>Sex:</td>
    <td><%= @bird.sex %></td>
  </tr>
  <tr>
    <td>Description: </td>
    <td><%= @bird.description %></td>
  </tr>
</table>

<br>

<% requests = @bird.bird_rental_requests.order('start_date ASC') %>
<table>
  <tr>
    <th>Start Date</th>
    <th>End Date</th>
  </tr>
  <% requests.each do |request| %>
  <tr>
    <td> <%= request.start_date %> </td>
    <td> <%= request.end_date %> </td>
  </tr>
  <% end %>
</table>

<%= link_to "Edit Bird", edit_bird_url %>
<br>
<br>
<br>
<%= link_to "Request Bird", new_bird_rental_request_url %>

<br>
<br>
<br>
<footer> <%= link_to "FLOCKPAGE", birds_url %> </footer>

byebyebirdies/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Byebyebirdies</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>